baseURL = "http://arshadhs.github.io"
languageCode = "en-us"
title = "Arshad Siddiqui"
theme = "ananke"
[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'Technology'
  url = '/technology'
  weight = 20
[[menu.main]]
  name = 'Recipes'
  url = '/recipe'
  weight = 30  
[[menu.main]]
  name = 'Blog'
  url = '/blog'
  weight = 40  
[[menu.main]]
  name = 'Resume'
  url = '/resume'
  weight = 60  
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 70