title = "Arshad Siddiqui"
baseURL = "http://arshadhs.github.io"
languageCode = "en-us"
theme = "hugo-book"
#themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
pagination.pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
show_recent_posts = false
ignoreLogs = ['warning-goldmark-raw-html']

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  #description = "Siddiqui's"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/arshadhs"
  linkedin = "https://www.linkedin.com/in/arshadsiddiqui/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 0
